import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import Navbar from "./components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "LEM Db",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     
        
      <body className={`${outfit.className} h-screen overflow-hidden flex flex-col`}>
        
        <Navbar />
         <ToastContainer />
        <main className="flex-1 overflow-hidden">
         
          {children}
        </main>
      </body>
     
    </html>
  );
}
